version: '2'

services:
    nginx:
        image: nginx
        ports:
            - "8070:80"
        volumes:
            - ./:/app
            - ./site.conf:/etc/nginx/conf.d/default.conf

    php7:
        build: .
        volumes:
            - ./:/app:delegated
        environment:
            XDEBUG_CONFIG: "remote_host=192.168.5.14"

    composer:
        image: composer
        volumes:
          - ./:/app
        command: install

    mongodb:
        image: mongo
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ./data/db:/data/db
        ports:
            - 8080:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet